### ISSUE TITLE
Unable to detect pupil

### ISSUE THREAD

**Issue by maddy-nit** [antoinelame/GazeTracking#3]
@antoinelame 
I have ran this code on 3.7 and 2.6 but it is not detecting pupil in any version and it is not giving any error in console.
Please get the attached photo for reference.
Can you please help me.

![untitled](https://user-images.githubusercontent.com/6389697/53621266-fbee6900-3c1b-11e9-9e25-3399705fe569.png)

**Comment by antoinelame** [comment]
Hi @maddy-nit 

It's difficult for me to solve the problem without more information. You can contact me directly by email (available on my profile) so that we can work together on solving the problem. We need to dig deeper to get more information about errors in the algorithm. For the moment, the program is mainly calibrated according to my eyes and webcam. But we both have dark eyes, so you should normally have very good accuracy with the current algorithm.

We have to check:

- If there is no problem with Dlib’s facial landmark detector (shape_predictor_68_face_landmarks.dat). It's a good start to check if GazeTracking.eyes.frame_left is empty or not.
- If the threshold value in `image_processing()` method is correct according to your webcam/eyes

**Comment by antoinelame** [comment]
It should be fixed with the adding of auto-calibration (76aa16e18196b9a646941cafc6cf1ca0d05774b5).
